# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a0cb8c3c02daaebf5d28afd10517eaf60128bec556f5a80ed9b2ff14ba6b29b25259d7e856eeb557d9062927ef3f520284945c39539102d87901f2171a2188

test:
  secret_key_base: 2d1a0b2aaacb0fb53ea191c766e5292ec6367887955485b057a2ea2600e63c78453694ea5689c9031ba94a313869bc35089e55775a13641a957a14b8db55b5a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
